spring:
  application:
    name: 03orderClient
server:
  port: 11000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
#02ITEMCLIENT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule