server:
  port: 40000
spring:
  application:
    name: 20configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liuhongyu_admin/ceshi
          # username: 如果有用户名和密码
          # password：
          search-paths:
            - 21itemprovider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka/