server:
  port: 11111
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false  #不注册到其他的eureka
    fetch-registry: false #不从其他 eureka 同步数据
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
